weather_app/urls.py
from django.urls import path
from . import views

app_name ='weather_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('load/', views.load_date, name='load'),
]

weather_core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather_app.urls'))
]

weather_app/models.py
from django.db import models

class Weather(models.Model):
    city = models.CharField(max_length=64, blank=False, null=False, default='city')
    temp = models.FloatField()
    pressure = models.PositiveSmallIntegerField(null=True)
    date = models.DateTimeField(auto_now_add=True)

weather_app/views.py
from django.shortcuts import render
import requests
from datetime import datetime
from babel.dates import format_datetime
from .models import Weather

def home(request):
        if request.method == 'POST':
            city = request.POST.get('city')
        else:
            city = 'Łódź'

        api_key = 'a3c8518113db5c7bc4513414babcb42c'
        lang = 'pl'
        units = 'metric'
        day = format_datetime(datetime.now(), locale='pl')
        url = f'https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units={units}' \
              f'&lang={lang}'
        response = requests.get(url).json()
        try:
            temp = response['main']['temp']
            description = response['weather'][0]['description']
            icon = response['weather'][0]['icon']
            pressure = response['main']['pressure']
        except KeyError:
            description = 'Wprowadz poprawne dane'
            return render(request, 'weather_app/key_error.html',
                          {'description': description,
                             'city': city, 'day': day})

        weather = Weather(city=city, temp=temp, pressure=pressure, )
        weather.save()

        return render(request,'weather_app/home2.html',
                      {'temp': temp, 'description':description,
                       'icon':icon, 'city':city,'day':day, 'pressure':pressure})
def load_date(request):
    if request.method == 'POST':
        weather_data = request.FILES.get('weather_data')
        response = requests.get(weather_data, stream=True)
        with open('temp/weather_data.csv', 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        with open('temp/weather_data.csv', newline='') as f:
            csv_str = f.read()
        return render(request, 'weather_app/success.html', {'weather_data':weather_data, 'csv_str':csv_str})

    return render(request, 'weather_app/load_data.html')

templates/base.html
{% load static %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <title>Pogodynka</title>
</head>
<body>
<header>

</header>
<div id="weather_data">
    <h1>{{ day }}</h1>
    <h1>{{ description }}</h1>
    <h1>{{ temp }} °C</h1>
    <h1>{{ pressure }} hPa</h1>
    <h1>{{ city }}</h1>
    <img src="https://api.openweathermap.org/img/w/{{icon}}.png" width="100px">


<form method="POST">
    {% csrf_token %}
    <input type="text" placeholder="Miasto..." name="city">
    <button type="submit">OK</button><br>
</form>
<!--    <br>-->
<!--    <h1><a href="{% url 'weather_app:load' %}" class="button">Wprowadź własne dane</a></h1>-->
</div>

</body>
</html>

weather_app/templates/weather_app/chart.html
{% load static %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <title>Pogodynka</title>
</head>
<body>
<div id="weather_data">
    <h1>{{ day }}</h1>
    <h1>{{ description }}</h1>
    <h1>{{ temp }} °C</h1>
    <h1>{{ city }}</h1>
    <img src="https://api.openweathermap.org/img/w/{{icon}}.png" width="100px">

<form method="POST">
    {% csrf_token %}
    <input type="text" placeholder="Miasto..." name="city">
    <button type="submit">OK</button>
</form>

</div>

</body>
</html>

weather_app/templates/weather_app/home.html
{% load static %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <title>Pogodynka</title>
</head>
<body>
<div id="weather_data">
    <h1>{{ day }}</h1>
    <h1>{{ description }}</h1>
    <h1>{{ temp }} °C</h1>
    <h1>{{ city }}</h1>
    <img src="https://api.openweathermap.org/img/w/{{icon}}.png" width="100px">

<form method="POST">
    {% csrf_token %}
    <input type="text" placeholder="Miasto..." name="city">
    <button type="submit">OK</button>
</form>
</div>

</body>
</html>

weather_app/templates/weather_app/home2.html
{% extends 'base.html' %}

weather_app/templates/weather_app/key_error.html
{% load static %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <title>Pogodynka</title>
</head>
<body>
<header>

</header>
<div id="weather_data">
    <h1>{{ day }}</h1>
    <h1>{{ description }}</h1>
    <h1>{{ city }}</h1>
    <img src="static\media\1f972.png" width="100px">


<form method="POST">
    {% csrf_token %}
    <input type="text" placeholder="Miasto..." name="city">
    <button type="submit">OK</button><br>
</form>
<!--    <br>-->
<!--    <h1><a href="{% url 'weather_app:load' %}" class="button">Wprowadź własne dane</a></h1>-->
</div>

</body>
</html>

weather_app/templates/weather_app/load_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Load</title>
</head>
<body>
<div>
<h1>{{ name }}</h1>
Wprowadź plik z danymi
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" placeholder="plik" name="weather_data">
    <button type="submit" value="upload">OK</button>
</form>
</div>
</body>
</html>